[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "nba-chatbot"
description = "NBA Chatbot"
version = "0.1.0"
dependencies = [
  "langchain",
  "langchain-community"
]

[project.scripts]
nba-chatbot = "nba-chatbot:main"