CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE player_per_game (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    rank INTEGER NOT NULL,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    age INTEGER NOT NULL,
    team TEXT NOT NULL,
    games INTEGER NOT NULL,
    games_started INTEGER NOT NULL,
    minutes_played NUMERIC NOT NULL,
    field_goals NUMERIC NOT NULL,
    field_goal_attempts NUMERIC NOT NULL,
    field_goal_pct NUMERIC,
    three_pointers NUMERIC NOT NULL,
    three_point_attempts NUMERIC NOT NULL,
    three_point_pct NUMERIC,
    two_pointers NUMERIC NOT NULL,
    two_point_attempts NUMERIC NOT NULL,
    two_point_pct NUMERIC,
    effective_fg_pct NUMERIC,
    free_throws NUMERIC NOT NULL,
    free_throw_attempts NUMERIC NOT NULL,
    free_throw_pct NUMERIC,
    offensive_rebounds NUMERIC NOT NULL,
    defensive_rebounds NUMERIC NOT NULL,
    total_rebounds NUMERIC NOT NULL,
    assists NUMERIC NOT NULL,
    steals NUMERIC NOT NULL,
    blocks NUMERIC NOT NULL,
    turnovers NUMERIC NOT NULL,
    personal_fouls NUMERIC NOT NULL,
    points NUMERIC NOT NULL,
    embedding vector(4096) NOT NULL
);
